In [32]:
import os
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import layers
import datetime
import timeit
import itertools

In [4]:
np.set_printoptions(precision=3, suppress=True)

In [5]:
abalone_train = pd.read_csv(
    "https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv",
    names=["Length", "Diameter", "Height", "Whole weight", "Shucked weight",
           "Viscera weight", "Shell weight", "Age"])

abalone_train.head()

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   0.435     0.335   0.110         0.334          0.1355          0.0775   
1   0.585     0.450   0.125         0.874          0.3545          0.2075   
2   0.655     0.510   0.160         1.092          0.3960          0.2825   
3   0.545     0.425   0.125         0.768          0.2940          0.1495   
4   0.545     0.420   0.130         0.879          0.3740          0.1695   

   Shell weight  Age  
0        0.0965    7  
1        0.2250    6  
2        0.3700   14  
3        0.2600   16  
4        0.2300   13

In [6]:
abalone_features = abalone_train.copy()
abalone_labels = abalone_features.pop('Age')

In [7]:
abalone_features = np.array(abalone_features)
abalone_features

array([[0.435, 0.335, 0.11 , ..., 0.136, 0.077, 0.097],
       [0.585, 0.45 , 0.125, ..., 0.354, 0.207, 0.225],
       [0.655, 0.51 , 0.16 , ..., 0.396, 0.282, 0.37 ],
       ...,
       [0.53 , 0.42 , 0.13 , ..., 0.374, 0.167, 0.249],
       [0.395, 0.315, 0.105, ..., 0.118, 0.091, 0.119],
       [0.45 , 0.355, 0.12 , ..., 0.115, 0.067, 0.16 ]])

In [8]:
abalone_model = tf.keras.Sequential([
  layers.Dense(64),
  layers.Dense(1)
])

abalone_model.compile(loss = tf.keras.losses.MeanSquaredError(),
                      optimizer = tf.keras.optimizers.Adam())

In [9]:
abalone_model.fit(abalone_features, abalone_labels, epochs=10)

Epoch 1/10
104/104 [==============================] - 1s 895us/step - loss: 59.0477
Epoch 2/10
104/104 [==============================] - 0s 849us/step - loss: 11.7166
Epoch 3/10
104/104 [==============================] - 0s 880us/step - loss: 8.9650
Epoch 4/10
104/104 [==============================] - 0s 855us/step - loss: 8.3748
Epoch 5/10
104/104 [==============================] - 0s 968us/step - loss: 7.8638
Epoch 6/10
104/104 [==============================] - 0s 912us/step - loss: 7.4363
Epoch 7/10
104/104 [==============================] - 0s 897us/step - loss: 7.1206
Epoch 8/10
104/104 [==============================] - 0s 935us/step - loss: 6.8780
Epoch 9/10
104/104 [==============================] - 0s 1ms/step - loss: 6.7243
Epoch 10/10
104/104 [==============================] - 0s 894us/step - loss: 6.5808


In [11]:
normalize = layers.Normalization()

In [12]:
normalize.adapt(abalone_features)

In [13]:
norm_abalone_model = tf.keras.Sequential([
  normalize,
  layers.Dense(64),
  layers.Dense(1)
])

norm_abalone_model.compile(loss = tf.keras.losses.MeanSquaredError(),
                           optimizer = tf.keras.optimizers.Adam())

norm_abalone_model.fit(abalone_features, abalone_labels, epochs=10)

Epoch 1/10
104/104 [==============================] - 0s 792us/step - loss: 92.4644
Epoch 2/10
104/104 [==============================] - 0s 794us/step - loss: 53.4980
Epoch 3/10
104/104 [==============================] - 0s 906us/step - loss: 16.4153
Epoch 4/10
104/104 [==============================] - 0s 944us/step - loss: 5.8460
Epoch 5/10
104/104 [==============================] - 0s 801us/step - loss: 5.0819
Epoch 6/10
104/104 [==============================] - 0s 771us/step - loss: 5.0071
Epoch 7/10
104/104 [==============================] - 0s 816us/step - loss: 5.0040
Epoch 8/10
104/104 [==============================] - 0s 916us/step - loss: 4.9743
Epoch 9/10
104/104 [==============================] - 0s 828us/step - loss: 4.9389
Epoch 10/10
104/104 [==============================] - 0s 888us/step - loss: 4.9554


In [14]:
titanic = pd.read_csv("https://storage.googleapis.com/tf-datasets/titanic/train.csv")
titanic.head()

survived     sex   age  n_siblings_spouses  parch     fare  class     deck  \
0         0    male  22.0                   1      0   7.2500  Third  unknown   
1         1  female  38.0                   1      0  71.2833  First        C   
2         1  female  26.0                   0      0   7.9250  Third  unknown   
3         1  female  35.0                   1      0  53.1000  First        C   
4         0    male  28.0                   0      0   8.4583  Third  unknown   

   embark_town alone  
0  Southampton     n  
1    Cherbourg     n  
2  Southampton     y  
3  Southampton     n  
4   Queenstown     y

In [15]:
titanic_features = titanic.copy()
titanic_labels = titanic_features.pop('survived')

In [16]:
input = tf.keras.Input(shape=(), dtype=tf.float32)
result = 2*input + 1
result

<KerasTensor: shape=(None,) dtype=float32 (created by layer 'tf.__operators__.add')>

In [17]:
calc = tf.keras.Model(inputs=input, outputs=result)

In [18]:
print(calc(1).numpy())
print(calc(2).numpy())

3.0
5.0


In [19]:
inputs = {}

for name, column in titanic_features.items():
    dtype = column.dtype
    if dtype == object:
        dtype = tf.string
    else:
        dtype = tf.float32
    inputs[name] = tf.keras.Input(shape=(1,), name=name, dtype=dtype)

inputs

{'sex': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'sex')>,
 'age': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'age')>,
 'n_siblings_spouses': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'n_siblings_spouses')>,
 'parch': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'parch')>,
 'fare': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'fare')>,
 'class': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'class')>,
 'deck': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'deck')>,
 'embark_town': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'embark_town')>,
 'alone': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'alone')>}

In [20]:
numeric_inputs = {name:input for name,input in inputs.items()
                  if input.dtype==tf.float32}

x = layers.Concatenate()(list(numeric_inputs.values()))
norm = layers.Normalization()
norm.adapt(np.array(titanic[numeric_inputs.keys()]))
all_numeric_inputs = norm(x)

all_numeric_inputs

<KerasTensor: shape=(None, 4) dtype=float32 (created by layer 'normalization_2')>

In [21]:
preprocessed_inputs = [all_numeric_inputs]

In [24]:
for name, input in inputs.items():
    if input.dtype == tf.float32:
        continue

    lookup = layers.StringLookup(vocabulary=np.unique(titanic_features[name]))
    one_hot = layers.CategoryEncoding(num_tokens=lookup.vocabulary_size())

    x = lookup(input)
    x = one_hot(x)
    preprocessed_inputs.append(x)

In [26]:
preprocessed_inputs_cat = layers.Concatenate()(preprocessed_inputs)
titanic_preprocessing = tf.keras.Model(inputs, preprocessed_inputs_cat)
tf.keras.utils.plot_model(model = titanic_preprocessing , rankdir="LR", dpi=72, show_shapes=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [27]:
titanic_features_dict = {name: np.array(value) 
                         for name, value in titanic_features.items()}

In [28]:
features_dict = {name:values[:1] for name, values in titanic_features_dict.items()}
titanic_preprocessing(features_dict)

<tf.Tensor: shape=(1, 52), dtype=float32, numpy=
array([[-0.61 ,  0.395, -0.479, -0.497,  0.   ,  0.   ,  1.   ,  0.   ,
         0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  1.   ,
         0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,
         0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  1.   ,
         0.   ,  0.   ,  1.   ,  0.   ]], dtype=float32)>

In [29]:
def titanic_model(preprocessing_head, inputs):
    body = tf.keras.Sequential([
        layers.Dense(64),
        layers.Dense(1)
    ])

    preprocessed_inputs = preprocessing_head(inputs)
    result = body(preprocessed_inputs)
    model = tf.keras.Model(inputs, result)

    model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True), optimizer=tf.keras.optimizers.Adam())
    return model

titanic_model = titanic_model(titanic_preprocessing, inputs)

In [30]:
titanic_model.fit(x=titanic_features_dict, y=titanic_labels, epochs=10)

Epoch 1/10
20/20 [==============================] - 1s 1ms/step - loss: 0.5619
Epoch 2/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4829
Epoch 3/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4487
Epoch 4/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4333
Epoch 5/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4286
Epoch 6/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4236
Epoch 7/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4218
Epoch 8/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4228
Epoch 9/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4218
Epoch 10/10
20/20 [==============================] - 0s 1ms/step - loss: 0.4203


In [31]:
titanic_model.save('test')
reloaded = tf.keras.models.load_model('test')

INFO:tensorflow:Assets written to: test\assets


INFO:tensorflow:Assets written to: test\assets


In [35]:
import itertools

def slices(features):
    for i in itertools.count():
        example = {name:values[i] for name, values in features.items()}
        yield example

In [36]:
for example in slices(titanic_features_dict):
    for name, value in example.items():
        print(f"{name:19s}: {value}")
    break


sex                : male
age                : 22.0
n_siblings_spouses : 1
parch              : 0
fare               : 7.25
class              : Third
deck               : unknown
embark_town        : Southampton
alone              : n


In [37]:
features_ds = tf.data.Dataset.from_tensor_slices(titanic_features_dict)

In [38]:
for example in features_ds:
    for name, value in example.items():
        print(f"{name:19s}: {value}")
    break

sex                : b'male'
age                : 22.0
n_siblings_spouses : 1
parch              : 0
fare               : 7.25
class              : b'Third'
deck               : b'unknown'
embark_town        : b'Southampton'
alone              : b'n'


In [39]:
titanic_ds = tf.data.Dataset.from_tensor_slices((titanic_features_dict, titanic_labels))

In [40]:
titanic_batches = titanic_ds.shuffle(len(titanic_labels)).batch(32)

In [41]:
titanic_model.fit(titanic_batches, epochs=5)

Epoch 1/5
20/20 [==============================] - 0s 1ms/step - loss: 0.4201
Epoch 2/5
20/20 [==============================] - 0s 1ms/step - loss: 0.4209
Epoch 3/5
20/20 [==============================] - 0s 2ms/step - loss: 0.4210
Epoch 4/5
20/20 [==============================] - 0s 1ms/step - loss: 0.4181
Epoch 5/5
20/20 [==============================] - 0s 1ms/step - loss: 0.4190


In [42]:
titanic_file_path = tf.keras.utils.get_file("train.csv", "https://storage.googleapis.com/tf-datasets/titanic/train.csv")

30874/30874 [==============================] - 0s 0us/step


In [43]:
titanic_csv_ds = tf.data.experimental.make_csv_dataset(
    titanic_file_path,
    batch_size=5, # Artificially small to make examples easier to show.
    label_name='survived',
    num_epochs=1,
    ignore_errors=True,)

Instructions for updating:
Use `tf.data.Dataset.ignore_errors` instead.


Instructions for updating:
Use `tf.data.Dataset.ignore_errors` instead.


In [45]:
for batch, label in titanic_csv_ds.take(1):
    for key, value in batch.items():
        print(f"{key:20s}: {value}")
    print()
    print(f"{'label':20s}: {label}")

sex                 : [b'male' b'male' b'female' b'male' b'male']
age                 : [20.  70.5  5.  21.  32. ]
n_siblings_spouses  : [0 0 2 0 0]
parch               : [0 0 1 0 0]
fare                : [ 8.05   7.75  19.258 73.5    7.854]
class               : [b'Third' b'Third' b'Third' b'Second' b'Third']
deck                : [b'unknown' b'unknown' b'unknown' b'unknown' b'unknown']
embark_town         : [b'Southampton' b'Queenstown' b'Cherbourg' b'Southampton' b'Southampton']
alone               : [b'y' b'y' b'n' b'y' b'y']

label               : [0 0 1 0 1]


In [46]:
traffic_volume_csv_gz = tf.keras.utils.get_file(
    'Metro_Interstate_Traffic_Volume.csv.gz', 
    "https://archive.ics.uci.edu/ml/machine-learning-databases/00492/Metro_Interstate_Traffic_Volume.csv.gz",
    cache_dir='.', cache_subdir='traffic')

405373/405373 [==============================] - 1s 2us/step


In [47]:
traffic_volume_csv_gz_ds = tf.data.experimental.make_csv_dataset(
    traffic_volume_csv_gz,
    batch_size=256,
    label_name='traffic_volume',
    num_epochs=1,
    compression_type="GZIP")

for batch, label in traffic_volume_csv_gz_ds.take(1):
    for key, value in batch.items():
        print(f"{key:20s}: {value[:5]}")
    print()
    print(f"{'label':20s}: {label[:5]}")

holiday             : [b'None' b'None' b'None' b'None' b'None']
temp                : [276.82 290.56 286.93 289.63 292.79]
rain_1h             : [0.   0.   3.98 0.   0.  ]
snow_1h             : [0. 0. 0. 0. 0.]
clouds_all          : [ 1  1 92 56 88]
weather_main        : [b'Clear' b'Clear' b'Mist' b'Clouds' b'Clouds']
weather_description : [b'sky is clear' b'sky is clear' b'mist' b'broken clouds'
 b'overcast clouds']
date_time           : [b'2013-05-14 03:00:00' b'2013-05-25 13:00:00' b'2013-10-05 00:00:00'
 b'2013-10-11 10:00:00' b'2013-09-11 00:00:00']

label               : [ 344 4537 1065 4813  570]


In [48]:
%%time
for i, (batch, label) in enumerate(traffic_volume_csv_gz_ds.repeat(20)):
    if i % 40 == 0:
        print('.', end='')
print()

...............................................................................................
CPU times: total: 10.6 s
Wall time: 6.5 s


In [49]:
%%time
caching = traffic_volume_csv_gz_ds.cache().shuffle(1000)
for i, (batch, label) in enumerate(caching.shuffle(1000).repeat(20)):
    if i % 40 == 0:
        print('.', end='')
print()

...............................................................................................
CPU times: total: 1.22 s
Wall time: 1 s


In [50]:
%%time
snapshotting = traffic_volume_csv_gz_ds.snapshot('titanic.tfsnap').shuffle(1000)

for i, (batch, label) in enumerate(snapshotting.shuffle(1000).repeat(20)):
    if i % 40 == 0:
        print('.', end='')
print()

...............................................................................................
CPU times: total: 2.39 s
Wall time: 1.43 s
